version: '3.8'

services:
  monitoring:
    build: .
    container_name: monitoring_app
    ports:
      - "8000:8000"
    volumes:
      # Les chemins sont montés selon la configuration dans settings.py
      - ${BACKUP_PATH:-/srv/backups}:${BACKUP_STORAGE_ROOT:-/monitoring/Backup}
      - ${VALIDATE_PATH:-/srv/validate}:${VALIDATED_BACKUPS_BASE_PATH:-/monitoring/Validate}
      - ${DB_PATH:-/srv/database}:/monitoring/data/db

    environment:
      - BACKUP_STORAGE_ROOT=${BACKUP_STORAGE_ROOT:-/monitoring/Backup}
      - VALIDATED_BACKUPS_BASE_PATH=${VALIDATED_BACKUPS_BASE_PATH:-/monitoring/Validate}
      - DATABASE_URL=${DATABASE_URL:-sqlite:////monitoring/data/db/sql_app.db}

    restart: unless-stopped


