"""Ajout du champ expected_hash à la table backupEntry

Revision ID: 189d154d9780
Revises: 00e32758568b
Create Date: 2025-06-20 00:40:51.654534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189d154d9780'
down_revision: Union[str, None] = '00e32758568b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_entries', sa.Column('expected_hash', sa.String(), nullable=True))
    op.drop_column('backup_entries', 'calculated_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_entries', sa.Column('calculated_hash', sa.VARCHAR(), nullable=True))
    op.drop_column('backup_entries', 'expected_hash')
    # ### end Alembic commands ###
